//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2eme_projet.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2eme_projet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _007674d7_116a_432f_81e4_93711345ecb2 {
            get {
                object obj = ResourceManager.GetObject("007674d7-116a-432f-81e4-93711345ecb2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06a71f80a6da7e79d72f72090089a26e {
            get {
                object obj = ResourceManager.GetObject("06a71f80a6da7e79d72f72090089a26e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06a71f80a6da7e79d72f72090089a26e1 {
            get {
                object obj = ResourceManager.GetObject("06a71f80a6da7e79d72f72090089a26e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0e3af68d_6301_4159_8b74_43a0abdd1669 {
            get {
                object obj = ResourceManager.GetObject("0e3af68d-6301-4159-8b74-43a0abdd1669", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0e3af68d_6301_4159_8b74_43a0abdd1669_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("0e3af68d-6301-4159-8b74-43a0abdd1669-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1024px_Tramway_de_Québec__1897____Cercle_blanc_svg_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("1024px-Tramway_de_Québec__1897__-_Cercle_blanc.svg-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _127911185 {
            get {
                object obj = ResourceManager.GetObject("127911185", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1279111851 {
            get {
                object obj = ResourceManager.GetObject("1279111851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _18915035_6102_421f_b703_6cf448569754 {
            get {
                object obj = ResourceManager.GetObject("18915035-6102-421f-b703-6cf448569754", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20210416_165948_1_ {
            get {
                object obj = ResourceManager.GetObject("20210416_165948[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20210416_170018_1_ {
            get {
                object obj = ResourceManager.GetObject("20210416_170018[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _210260g {
            get {
                object obj = ResourceManager.GetObject("210260g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _210260g_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("210260g-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22e113f3_f70a_4036_b7c7_999190666f95 {
            get {
                object obj = ResourceManager.GetObject("22e113f3-f70a-4036-b7c7-999190666f95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25322644_26660870 {
            get {
                object obj = ResourceManager.GetObject("25322644-26660870", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2657ffbd_1964_4111_9493_b51f0fb46772 {
            get {
                object obj = ResourceManager.GetObject("2657ffbd-1964-4111-9493-b51f0fb46772", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _392001500_EYES_EMOJI_400px {
            get {
                object obj = ResourceManager.GetObject("392001500_EYES_EMOJI_400px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3949337 {
            get {
                object obj = ResourceManager.GetObject("3949337", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39493371 {
            get {
                object obj = ResourceManager.GetObject("39493371", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39493372 {
            get {
                object obj = ResourceManager.GetObject("39493372", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _396_3965468_puma_logo_png_transparent_puma_logopng_images_pluspng_puma_logo_png_transparent {
            get {
                object obj = ResourceManager.GetObject("396-3965468_puma-logo-png-transparent-puma-logopng-images-pluspng-puma-logo-png-t" +
                        "ransparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _396_3965468_puma_logo_png_transparent_puma_logopng_images_pluspng_puma_logo_png_transparent1 {
            get {
                object obj = ResourceManager.GetObject("396-3965468_puma-logo-png-transparent-puma-logopng-images-pluspng-puma-logo-png-t" +
                        "ransparent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _396_3965468_puma_logo_png_transparent_puma_logopng_images_pluspng_puma_logo_png_transparent2 {
            get {
                object obj = ResourceManager.GetObject("396-3965468_puma-logo-png-transparent-puma-logopng-images-pluspng-puma-logo-png-t" +
                        "ransparent2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3d04611a_7c68_47a1_95d2_72f3f6d6ec15 {
            get {
                object obj = ResourceManager.GetObject("3d04611a-7c68-47a1-95d2-72f3f6d6ec15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3d04611a_7c68_47a1_95d2_72f3f6d6ec151 {
            get {
                object obj = ResourceManager.GetObject("3d04611a-7c68-47a1-95d2-72f3f6d6ec151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4069aadfd0ba742f05dd274f2f068351 {
            get {
                object obj = ResourceManager.GetObject("4069aadfd0ba742f05dd274f2f068351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5cb4aad3_ac64_40d5_af27_9eb0e8ef4cdf {
            get {
                object obj = ResourceManager.GetObject("5cb4aad3-ac64-40d5-af27-9eb0e8ef4cdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _638bb305_c191_4681_afa4_9396f55b72dc {
            get {
                object obj = ResourceManager.GetObject("638bb305-c191-4681-afa4-9396f55b72dc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6432cca9_9b13_4564_ba02_557c222fadd8 {
            get {
                object obj = ResourceManager.GetObject("6432cca9-9b13-4564-ba02-557c222fadd8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _65_655052_puma_logo_png_transparent_images_puma {
            get {
                object obj = ResourceManager.GetObject("65-655052_puma-logo-png-transparent-images-puma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _705d86d01a966ff8f2e1e0ed1c9c6bef_icon {
            get {
                object obj = ResourceManager.GetObject("705d86d01a966ff8f2e1e0ed1c9c6bef_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _705d86d01a966ff8f2e1e0ed1c9c6bef_icon1 {
            get {
                object obj = ResourceManager.GetObject("705d86d01a966ff8f2e1e0ed1c9c6bef_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _705d86d01a966ff8f2e1e0ed1c9c6bef_icon2 {
            get {
                object obj = ResourceManager.GetObject("705d86d01a966ff8f2e1e0ed1c9c6bef_icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80752890_website_contact_us_icons_on_brown_tags_over_grey_background_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("80752890-website-contact-us-icons-on-brown-tags-over-grey-background-removebg-pre" +
                        "view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84447316_1941_455b_8aaa_6cf0532f78c3 {
            get {
                object obj = ResourceManager.GetObject("84447316-1941-455b-8aaa-6cf0532f78c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _873ad6f2_0fca_43fa_89ef_79ea4fdc544f {
            get {
                object obj = ResourceManager.GetObject("873ad6f2-0fca-43fa-89ef-79ea4fdc544f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _873ad6f2_0fca_43fa_89ef_79ea4fdc544f1 {
            get {
                object obj = ResourceManager.GetObject("873ad6f2-0fca-43fa-89ef-79ea4fdc544f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _873ad6f2_0fca_43fa_89ef_79ea4fdc544f2 {
            get {
                object obj = ResourceManager.GetObject("873ad6f2-0fca-43fa-89ef-79ea4fdc544f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _873ad6f2_0fca_43fa_89ef_79ea4fdc544f3 {
            get {
                object obj = ResourceManager.GetObject("873ad6f2-0fca-43fa-89ef-79ea4fdc544f3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _873ad6f2_0fca_43fa_89ef_79ea4fdc544f4 {
            get {
                object obj = ResourceManager.GetObject("873ad6f2-0fca-43fa-89ef-79ea4fdc544f4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _873ad6f2_0fca_43fa_89ef_79ea4fdc544f5 {
            get {
                object obj = ResourceManager.GetObject("873ad6f2-0fca-43fa-89ef-79ea4fdc544f5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8f91401c_660a_4bad_9e61_d6e0c575b8e1 {
            get {
                object obj = ResourceManager.GetObject("8f91401c-660a-4bad-9e61-d6e0c575b8e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8f91401c_660a_4bad_9e61_d6e0c575b8e11 {
            get {
                object obj = ResourceManager.GetObject("8f91401c-660a-4bad-9e61-d6e0c575b8e11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8f91401c_660a_4bad_9e61_d6e0c575b8e12 {
            get {
                object obj = ResourceManager.GetObject("8f91401c-660a-4bad-9e61-d6e0c575b8e12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8f91401c_660a_4bad_9e61_d6e0c575b8e13 {
            get {
                object obj = ResourceManager.GetObject("8f91401c-660a-4bad-9e61-d6e0c575b8e13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9af69de6_4b2c_49f4_8fcd_bcbc96750b20 {
            get {
                object obj = ResourceManager.GetObject("9af69de6-4b2c-49f4-8fcd-bcbc96750b20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9af69de6_4b2c_49f4_8fcd_bcbc96750b20_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("9af69de6-4b2c-49f4-8fcd-bcbc96750b20-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_star {
            get {
                object obj = ResourceManager.GetObject("A_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a0636a7b_4bca_4e17_802b_7330f3e5cfee {
            get {
                object obj = ResourceManager.GetObject("a0636a7b-4bca-4e17-802b-7330f3e5cfee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a0636a7b_4bca_4e17_802b_7330f3e5cfee_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("a0636a7b-4bca-4e17-802b-7330f3e5cfee-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a63c831d_ddee_4f81_ac95_c6883c57871a {
            get {
                object obj = ResourceManager.GetObject("a63c831d-ddee-4f81-ac95-c6883c57871a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a63c831d_ddee_4f81_ac95_c6883c57871a1 {
            get {
                object obj = ResourceManager.GetObject("a63c831d-ddee-4f81-ac95-c6883c57871a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a63c831d_ddee_4f81_ac95_c6883c57871a2 {
            get {
                object obj = ResourceManager.GetObject("a63c831d-ddee-4f81-ac95-c6883c57871a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a7caa119_8b26_4894_962c_9973b18eaa46 {
            get {
                object obj = ResourceManager.GetObject("a7caa119-8b26-4894-962c-9973b18eaa46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a7caa119_8b26_4894_962c_9973b18eaa461 {
            get {
                object obj = ResourceManager.GetObject("a7caa119-8b26-4894-962c-9973b18eaa461", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a7caa119_8b26_4894_962c_9973b18eaa462 {
            get {
                object obj = ResourceManager.GetObject("a7caa119-8b26-4894-962c-9973b18eaa462", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ad33c8bb_65ff_4987_93fe_12068098160c {
            get {
                object obj = ResourceManager.GetObject("ad33c8bb-65ff-4987-93fe-12068098160c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ad33c8bb_65ff_4987_93fe_12068098160c1 {
            get {
                object obj = ResourceManager.GetObject("ad33c8bb-65ff-4987-93fe-12068098160c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ad33c8bb_65ff_4987_93fe_12068098160c2 {
            get {
                object obj = ResourceManager.GetObject("ad33c8bb-65ff-4987-93fe-12068098160c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated_check {
            get {
                object obj = ResourceManager.GetObject("animated-check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down_512 {
            get {
                object obj = ResourceManager.GetObject("arrow-down-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bcb706df_8c29_4aae_b2b6_0d75fa2a93d4 {
            get {
                object obj = ResourceManager.GetObject("bcb706df-8c29-4aae-b2b6-0d75fa2a93d4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bfc1e68d_c639_4426_acf7_a5e1fe702ceb {
            get {
                object obj = ResourceManager.GetObject("bfc1e68d-c639-4426-acf7-a5e1fe702ceb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc_removebg_preview2 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc-removebg-preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc_removebg_preview3 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc-removebg-preview3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc_removebg_preview4 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc-removebg-preview4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc1 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc2 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc3 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc4 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc5 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc6 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc7 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cadf6704_194d_4c55_a62c_2a4b1c6a04bc8 {
            get {
                object obj = ResourceManager.GetObject("cadf6704-194d-4c55-a62c-2a4b1c6a04bc8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb534b9d_9d18_41cf_bb4b_b19a7dc65934 {
            get {
                object obj = ResourceManager.GetObject("cb534b9d-9d18-41cf-bb4b-b19a7dc65934", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb534b9d_9d18_41cf_bb4b_b19a7dc659341 {
            get {
                object obj = ResourceManager.GetObject("cb534b9d-9d18-41cf-bb4b-b19a7dc659341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb534b9d_9d18_41cf_bb4b_b19a7dc659342 {
            get {
                object obj = ResourceManager.GetObject("cb534b9d-9d18-41cf-bb4b-b19a7dc659342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cercle_noir_318_9051_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("cercle-noir_318-9051-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check02 {
            get {
                object obj = ResourceManager.GetObject("check02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compte {
            get {
                object obj = ResourceManager.GetObject("compte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contact_us_graphic {
            get {
                object obj = ResourceManager.GetObject("contact-us-graphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d0914b40_c7b9_4e45_bd61_5196d0a29a40 {
            get {
                object obj = ResourceManager.GetObject("d0914b40-c7b9-4e45-bd61-5196d0a29a40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e20c0171_3cd8_4805_8f8e_6bf231e5f055 {
            get {
                object obj = ResourceManager.GetObject("e20c0171-3cd8-4805-8f8e-6bf231e5f055", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e8f8ff5e9edfb85d95dde093754e0728 {
            get {
                object obj = ResourceManager.GetObject("e8f8ff5e9edfb85d95dde093754e0728", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e8f8ff5e9edfb85d95dde093754e07281 {
            get {
                object obj = ResourceManager.GetObject("e8f8ff5e9edfb85d95dde093754e07281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e8f8ff5e9edfb85d95dde093754e07282 {
            get {
                object obj = ResourceManager.GetObject("e8f8ff5e9edfb85d95dde093754e07282", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e8f8ff5e9edfb85d95dde093754e07283 {
            get {
                object obj = ResourceManager.GetObject("e8f8ff5e9edfb85d95dde093754e07283", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e8f8ff5e9edfb85d95dde093754e07284 {
            get {
                object obj = ResourceManager.GetObject("e8f8ff5e9edfb85d95dde093754e07284", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eclaboussures_de_peinture_drapeau_du_lion_maroc {
            get {
                object obj = ResourceManager.GetObject("eclaboussures-de-peinture-drapeau-du-lion-maroc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eclaboussures_de_peinture_drapeau_du_lion_maroc1 {
            get {
                object obj = ResourceManager.GetObject("eclaboussures-de-peinture-drapeau-du-lion-maroc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eclaboussures_de_peinture_drapeau_du_lion_maroc2 {
            get {
                object obj = ResourceManager.GetObject("eclaboussures-de-peinture-drapeau-du-lion-maroc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eclaboussures_de_peinture_drapeau_du_lion_maroc3 {
            get {
                object obj = ResourceManager.GetObject("eclaboussures-de-peinture-drapeau-du-lion-maroc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eclaboussures_de_peinture_drapeau_du_lion_maroc4 {
            get {
                object obj = ResourceManager.GetObject("eclaboussures-de-peinture-drapeau-du-lion-maroc4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elegant_green_geometric_polygon_background_vector {
            get {
                object obj = ResourceManager.GetObject("elegant-green-geometric-polygon-background-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elegant_green_geometric_polygon_background_vector1 {
            get {
                object obj = ResourceManager.GetObject("elegant-green-geometric-polygon-background-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elegant_green_geometric_polygon_background_vector2 {
            get {
                object obj = ResourceManager.GetObject("elegant-green-geometric-polygon-background-vector2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elegant_green_geometric_polygon_background_vector3 {
            get {
                object obj = ResourceManager.GetObject("elegant-green-geometric-polygon-background-vector3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elegant_green_geometric_polygon_background_vector4 {
            get {
                object obj = ResourceManager.GetObject("elegant-green-geometric-polygon-background-vector4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f5d3830d_f6f9_4370_b97d_3a233e00d385 {
            get {
                object obj = ResourceManager.GetObject("f5d3830d-f6f9-4370-b97d-3a233e00d385", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f6a10d5b_aa00_405f_ab39_f06185583327 {
            get {
                object obj = ResourceManager.GetObject("f6a10d5b-aa00-405f-ab39-f06185583327", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f6a10d5b_aa00_405f_ab39_f061855833271 {
            get {
                object obj = ResourceManager.GetObject("f6a10d5b-aa00-405f-ab39-f061855833271", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f6a10d5b_aa00_405f_ab39_f061855833272 {
            get {
                object obj = ResourceManager.GetObject("f6a10d5b-aa00-405f-ab39-f061855833272", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f774d39a_b680_4c62_8007_316e4285ff48 {
            get {
                object obj = ResourceManager.GetObject("f774d39a-b680-4c62-8007-316e4285ff48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f774d39a_b680_4c62_8007_316e4285ff481 {
            get {
                object obj = ResourceManager.GetObject("f774d39a-b680-4c62-8007-316e4285ff481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f774d39a_b680_4c62_8007_316e4285ff482 {
            get {
                object obj = ResourceManager.GetObject("f774d39a-b680-4c62-8007-316e4285ff482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f774d39a_b680_4c62_8007_316e4285ff483 {
            get {
                object obj = ResourceManager.GetObject("f774d39a-b680-4c62-8007-316e4285ff483", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f774d39a_b680_4c62_8007_316e4285ff484 {
            get {
                object obj = ResourceManager.GetObject("f774d39a-b680-4c62-8007-316e4285ff484", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f988f04a_397f_4ea6_b3fb_96d6411eb748 {
            get {
                object obj = ResourceManager.GetObject("f988f04a-397f-4ea6-b3fb-96d6411eb748", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f988f04a_397f_4ea6_b3fb_96d6411eb7481 {
            get {
                object obj = ResourceManager.GetObject("f988f04a-397f-4ea6-b3fb-96d6411eb7481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f988f04a_397f_4ea6_b3fb_96d6411eb7482 {
            get {
                object obj = ResourceManager.GetObject("f988f04a-397f-4ea6-b3fb-96d6411eb7482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f9d104d2_0931_4cc2_a63d_fa6d2bbab11b {
            get {
                object obj = ResourceManager.GetObject("f9d104d2-0931-4cc2-a63d-fa6d2bbab11b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f9d104d2_0931_4cc2_a63d_fa6d2bbab11b_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("f9d104d2-0931-4cc2-a63d-fa6d2bbab11b-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f9d104d2_0931_4cc2_a63d_fa6d2bbab11b1 {
            get {
                object obj = ResourceManager.GetObject("f9d104d2-0931-4cc2-a63d-fa6d2bbab11b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grunge_du_maroc_vieux_rayé_drapeau_de_style_84521568 {
            get {
                object obj = ResourceManager.GetObject("grunge-du-maroc-vieux-rayé-drapeau-de-style-84521568", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap idata_0597811_PERSONNAGES_gif_anime_foot_2_gratuit {
            get {
                object obj = ResourceManager.GetObject("idata_0597811_PERSONNAGES_gif-anime-foot-2-gratuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("images__1_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_1 {
            get {
                object obj = ResourceManager.GetObject("images (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_2 {
            get {
                object obj = ResourceManager.GetObject("images (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_3 {
            get {
                object obj = ResourceManager.GetObject("images (1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2_ {
            get {
                object obj = ResourceManager.GetObject("images (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("images__2_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__4_ {
            get {
                object obj = ResourceManager.GetObject("images (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__5_ {
            get {
                object obj = ResourceManager.GetObject("images (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__6_ {
            get {
                object obj = ResourceManager.GetObject("images (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__7_ {
            get {
                object obj = ResourceManager.GetObject("images (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__8_ {
            get {
                object obj = ResourceManager.GetObject("images (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__8_1 {
            get {
                object obj = ResourceManager.GetObject("images (8)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__8_2 {
            get {
                object obj = ResourceManager.GetObject("images (8)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__8_3 {
            get {
                object obj = ResourceManager.GetObject("images (8)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images2 {
            get {
                object obj = ResourceManager.GetObject("images2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images3 {
            get {
                object obj = ResourceManager.GetObject("images3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_898295684_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-898295684-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nike_mercurial_vapor_12_game_over_4 {
            get {
                object obj = ResourceManager.GetObject("nike-mercurial-vapor-12-game-over-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nike_mercurial_vapor_12_game_over_41 {
            get {
                object obj = ResourceManager.GetObject("nike-mercurial-vapor-12-game-over-41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_eye_hiding_people_logo_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-eye-hiding-people-logo-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_eye_hiding_people_logo_thumbnail_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-eye-hiding-people-logo-thumbnail-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_eye_icon_image_1338426 {
            get {
                object obj = ResourceManager.GetObject("pngtree-eye-icon-image_1338426", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_eye_icon_image_1338426_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pngtree-eye-icon-image_1338426-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_marocco_flag_with_brush_strokes_style_for_national_day_png_image_2394618 {
            get {
                object obj = ResourceManager.GetObject("pngtree-marocco-flag-with-brush-strokes-style-for-national-day-png-image_2394618", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_marocco_flag_with_brush_strokes_style_for_national_day_png_image_2394618_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pngtree-marocco-flag-with-brush-strokes-style-for-national-day-png-image_2394618-" +
                        "removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_marocco_flag_with_brush_strokes_style_for_national_day_png_image_2394618_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("pngtree-marocco-flag-with-brush-strokes-style-for-national-day-png-image_2394618-" +
                        "removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap progressbar_indeterminate {
            get {
                object obj = ResourceManager.GetObject("progressbar-indeterminate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_icone_de_validation_coche_de_couleur_rouge_vector_illustration_vector_rc2hnx_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("red-icone-de-validation-coche-de-couleur-rouge-vector-illustration-vector-rc2hnx-" +
                        "removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shopping_cart_icon_svg {
            get {
                object obj = ResourceManager.GetObject("Shopping_cart_icon.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shopping_cart_icon1 {
            get {
                object obj = ResourceManager.GetObject("Shopping_cart_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé {
            get {
                object obj = ResourceManager.GetObject("téléchargé", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__1_ {
            get {
                object obj = ResourceManager.GetObject("téléchargé (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__1_1 {
            get {
                object obj = ResourceManager.GetObject("téléchargé (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__2_ {
            get {
                object obj = ResourceManager.GetObject("téléchargé (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__2_1 {
            get {
                object obj = ResourceManager.GetObject("téléchargé (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__2_2 {
            get {
                object obj = ResourceManager.GetObject("téléchargé (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__2_3 {
            get {
                object obj = ResourceManager.GetObject("téléchargé (2)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__2_4 {
            get {
                object obj = ResourceManager.GetObject("téléchargé (2)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__4_ {
            get {
                object obj = ResourceManager.GetObject("téléchargé (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé__4_1 {
            get {
                object obj = ResourceManager.GetObject("téléchargé (4)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap téléchargé1 {
            get {
                object obj = ResourceManager.GetObject("téléchargé1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb2_morocco_national_football_team_4k_geometric_art_logo_red_abstract_background {
            get {
                object obj = ResourceManager.GetObject("thumb2-morocco-national-football-team-4k-geometric-art-logo-red-abstract-backgrou" +
                        "nd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb2_morocco_national_football_team_4k_geometric_art_logo_red_abstract_background1 {
            get {
                object obj = ResourceManager.GetObject("thumb2-morocco-national-football-team-4k-geometric-art-logo-red-abstract-backgrou" +
                        "nd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb2_morocco_national_football_team_4k_geometric_art_logo_red_abstract_background2 {
            get {
                object obj = ResourceManager.GetObject("thumb2-morocco-national-football-team-4k-geometric-art-logo-red-abstract-backgrou" +
                        "nd2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed__1_ {
            get {
                object obj = ResourceManager.GetObject("unnamed (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_red_business_card_contact_600w_1027537153 {
            get {
                object obj = ResourceManager.GetObject("vector-red-business-card-contact-600w-1027537153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_13_at_20_07_35 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-13 at 20.07.35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_13_at_20_07_36 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-13 at 20.07.36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_13_at_20_07_36__1_ {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-13 at 20.07.36 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_14_at_21_54_10 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-14 at 21.54.10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_14_at_21_54_11 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-14 at 21.54.11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_14_at_21_541 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-14 at 21.541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2021_04_14_at_21_58_09 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2021-04-14 at 21.58.09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap World_Cup_Balls_2 {
            get {
                object obj = ResourceManager.GetObject("World-Cup-Balls_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
